// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0KKT0njQjkTahUJENa9iL900vfcYhyWI',
    appId: '1:282358758608:web:48a1d9668f17cdda2ef2d5',
    messagingSenderId: '282358758608',
    projectId: 'event-ci',
    authDomain: 'event-ci.firebaseapp.com',
    storageBucket: 'event-ci.firebasestorage.app',
    measurementId: 'G-CZQSMZGSBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrzjCGOw4gz_YP36MiUN_Q4F-SKUEvRak',
    appId: '1:282358758608:android:6794527b4d94bd922ef2d5',
    messagingSenderId: '282358758608',
    projectId: 'event-ci',
    storageBucket: 'event-ci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ3MSnJgd57WXvxdWbax3BTtWcHIo9Vk8',
    appId: '1:282358758608:ios:14f422ada77034922ef2d5',
    messagingSenderId: '282358758608',
    projectId: 'event-ci',
    storageBucket: 'event-ci.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ3MSnJgd57WXvxdWbax3BTtWcHIo9Vk8',
    appId: '1:282358758608:ios:14f422ada77034922ef2d5',
    messagingSenderId: '282358758608',
    projectId: 'event-ci',
    storageBucket: 'event-ci.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0KKT0njQjkTahUJENa9iL900vfcYhyWI',
    appId: '1:282358758608:web:439d4ca580585fb12ef2d5',
    messagingSenderId: '282358758608',
    projectId: 'event-ci',
    authDomain: 'event-ci.firebaseapp.com',
    storageBucket: 'event-ci.firebasestorage.app',
    measurementId: 'G-T2MTNDTE64',
  );
}
